version: '3.7'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}      
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
  web:
    build: ./app
    container_name: app
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    command: /app/start.sh

volumes:
  db_data:
