# Generated by Django 3.2.8 on 2022-02-18 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество продукта'),
        ),
    ]
