# Generated by Django 3.2.8 on 2022-02-22 00:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('title',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
