# Generated by Django 3.2.8 on 2022-02-22 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0002_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('recipe', 'product')},
        ),
    ]
