# Generated by Django 3.2.8 on 2022-02-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_alter_recipeingredient_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='Ingredient',
        ),
    ]
